from plyfile import PlyData, PlyElement
import numpy as np

""" 
Contents of the gaussian splat PLY:

ply
format binary_little_endian 1.0
comment Generated by Nerstudio 1.1.5
comment Vertical Axis: z
element vertex 500478
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header

The goal is to add class_id to the PLY file: 

property list uchar float class_id

At first, we assume a class limit of 3, so every class_id is size 3.
"""

sparse_ply = "../data/nerfstudio/garden_8/sparse_pc.ply"
gaussian_ply = "../data/.temp/splat.ply"

plydata = PlyData.read(gaussian_ply)

print('element 0 name', plydata.elements[0].name)
print('element 0 to list', plydata.elements[0].data[0].tolist())
print('x', plydata.elements[0].data['x'])
print('opacity', plydata['vertex'].data['opacity'][0])
print('x convenience', plydata['vertex']['x'])
print('direct access', plydata['vertex'][0].tolist())
print('metadata properties', plydata.elements[0].properties)
print('element 0 count', plydata.elements[0].count)